### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bzrampurawala** [weisjohn/mongoose-csv#12]
node_modules\mongoose-csv\node_modules\map-stream\index.js:103
        throw err
        ^

RangeError: Maximum call stack size exceeded
    at emitOne (events.js:121:20)
    at Stream.emit (events.js:211:7)
    at next (node_modules\mongoose-csv\node_modules\map-stream\index.js:75:19)
    at Stream.stream.write (node_modules\mongoose-csv\node_modules\map-stream\index.js:104:7)
    at QueryCursor.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at QueryCursor.emit (events.js:211:7)
    at QueryCursor.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at Stream.<anonymous> (_stream_readable.js:707:7)
    at emitNone (events.js:106:13)
    at Stream.emit (events.js:208:7)
    at queueData (node_modules\mongoose-csv\node_modules\map-stream\index.js:61:41)
    at next (node_modules\mongoose-csv\node_modules\map-stream\index.js:71:7)
    at node_modules\mongoose-csv\node_modules\map-stream\index.js:85:7
    at node_modules\mongoose-csv\index.js:51:17

I get this error every time I try to get CSV file.

**Comment by ThePenguin1140** [comment]
Setting a limit on the query will fix this. The limit that works for is around 100 rows though which is very low.
👍
